site_name: PaginaDocs
nav:
  - Home: index.md
  - Sobre: about.md
  - Vinda: vinda.md
  - Guia de Instalação: install.md
  - Configuração: config.md
  - FAQ: faq.md
theme:
   name: material
features:
  - navigation.tabs
  - navigation.top
palette:
  - scheme: default
  - primary: indigo
  - accent: blue
